// <auto-generated />
using System;
using AllocationRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllocationRepository.Migrations
{
    [DbContext(typeof(AllocationDbContext))]
    [Migration("20251104081859_updateatributedb")]
    partial class updateatributedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllocationRepository.Model.Allocations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleInstanceId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("AllocationRepository.Model.EVInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VehicleInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleInstanceId");

                    b.ToTable("EVInventories");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehicleInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleInstances");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehicleOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehicleOptions");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehiclePrices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehiclePrices");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehiclePromotions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehiclePromotions");
                });

            modelBuilder.Entity("AllocationRepository.Model.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RangeKM")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleOptionId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AllocationRepository.Model.Allocations", b =>
                {
                    b.HasOne("AllocationRepository.Model.VehicleInstance", "VehicleInstance")
                        .WithMany("Allocations")
                        .HasForeignKey("VehicleInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleInstance");
                });

            modelBuilder.Entity("AllocationRepository.Model.EVInventory", b =>
                {
                    b.HasOne("AllocationRepository.Model.VehicleInstance", "VehicleInstance")
                        .WithMany("EVInventories")
                        .HasForeignKey("VehicleInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleInstance");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehicleInstance", b =>
                {
                    b.HasOne("AllocationRepository.Model.Vehicles", "Vehicle")
                        .WithMany("VehicleInstances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehiclePrices", b =>
                {
                    b.HasOne("AllocationRepository.Model.Vehicles", "Vehicle")
                        .WithMany("VehiclePrices")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehiclePromotions", b =>
                {
                    b.HasOne("AllocationRepository.Model.Vehicles", "Vehicle")
                        .WithMany("VehiclePromotions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AllocationRepository.Model.Vehicles", b =>
                {
                    b.HasOne("AllocationRepository.Model.VehicleOptions", "VehicleOption")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleOption");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehicleInstance", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("EVInventories");
                });

            modelBuilder.Entity("AllocationRepository.Model.VehicleOptions", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AllocationRepository.Model.Vehicles", b =>
                {
                    b.Navigation("VehicleInstances");

                    b.Navigation("VehiclePrices");

                    b.Navigation("VehiclePromotions");
                });
#pragma warning restore 612, 618
        }
    }
}
