// <auto-generated />
using System;
using AnalyticRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticRepository.Migrations
{
    [DbContext(typeof(AnalyticDbContext))]
    partial class AnalyticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnalyticRepository.Model.EtlLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("LastStatusMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSuccessfulRun")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EtlLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRunning = false,
                            LastStatusMessage = "Service starting."
                        });
                });

            modelBuilder.Entity("AnalyticRepository.Model.Monthly_Demand_Features", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<int>("AgencyOrdersQuantity")
                        .HasColumnType("int");

                    b.Property<string>("AgencyRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgencyTarget")
                        .HasColumnType("int");

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("PromotionDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuotationsAcceptedCount")
                        .HasColumnType("int");

                    b.Property<double>("RollingAvgSales3Months")
                        .HasColumnType("float");

                    b.Property<double>("RollingAvgSales6Months")
                        .HasColumnType("float");

                    b.Property<int>("TestDrivesCount")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSoldLastMonth")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSoldSameMonthLastYear")
                        .HasColumnType("int");

                    b.Property<string>("VehicleBatteryCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleRangeKM")
                        .HasColumnType("int");

                    b.Property<bool>("WasOnPromotion")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonthlyDemandFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
